-- Run this once in the Supabase SQL Editor after rich-player-migration.sql.
-- Football players stay in public.players. Cricket players use their own table
-- because their roles, profiles and card attributes are different.

begin;

alter table public.squad_settings
  add column if not exists sport_mode text not null default 'football';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'squad_settings_sport_mode_check'
      and conrelid = 'public.squad_settings'::regclass
  ) then
    alter table public.squad_settings
      add constraint squad_settings_sport_mode_check
      check (sport_mode in ('football', 'cricket'));
  end if;
end $$;

create or replace function public.sync_squad_sheet_sport_mode()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.sport_mode := case
    when new.app_state->>'sportMode' = 'cricket' then 'cricket'
    else 'football'
  end;
  return new;
end;
$$;

drop trigger if exists squad_settings_sync_sport_mode on public.squad_settings;
create trigger squad_settings_sync_sport_mode
before insert or update of app_state on public.squad_settings
for each row execute function public.sync_squad_sheet_sport_mode();

update public.squad_settings
set sport_mode = case
  when app_state->>'sportMode' = 'cricket' then 'cricket'
  else 'football'
end
where id = 1;

create table if not exists public.cricket_players (
  id bigint generated by default as identity primary key,
  client_id text not null unique,
  name text not null,
  rating numeric(3,1) not null default 0,
  custom_overall integer,
  overall integer,
  role text not null default 'All-rounder',
  batting_order integer not null default 6,
  batting_hand text not null default 'Right hand',
  bowling_style text not null default 'Right-arm medium',
  image_url text,
  flag text not null default 'PK',
  card_style text not null default 'electric',
  active boolean not null default true,
  batting integer,
  bowling integer,
  fielding integer,
  speed integer,
  power integer,
  technique integer,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cricket_players_name_check check (char_length(btrim(name)) between 1 and 60),
  constraint cricket_players_rating_check check (rating between 0 and 10 and rating * 2 = trunc(rating * 2)),
  constraint cricket_players_custom_overall_check check (custom_overall is null or custom_overall between 1 and 99),
  constraint cricket_players_overall_check check (overall is null or overall between 1 and 99),
  constraint cricket_players_role_check check (role in ('Batter', 'Bowler', 'All-rounder', 'Wicketkeeper')),
  constraint cricket_players_batting_order_check check (batting_order between 1 and 11),
  constraint cricket_players_batting_hand_check check (batting_hand in ('Right hand', 'Left hand')),
  constraint cricket_players_card_style_check check (card_style in ('electric', 'classic', 'eclipse', 'crimson')),
  constraint cricket_players_batting_check check (batting is null or batting between 1 and 99),
  constraint cricket_players_bowling_check check (bowling is null or bowling between 1 and 99),
  constraint cricket_players_fielding_check check (fielding is null or fielding between 1 and 99),
  constraint cricket_players_speed_check check (speed is null or speed between 1 and 99),
  constraint cricket_players_power_check check (power is null or power between 1 and 99),
  constraint cricket_players_technique_check check (technique is null or technique between 1 and 99)
);

alter table public.cricket_players
  add column if not exists batting_order integer not null default 6;
alter table public.cricket_players
  drop constraint if exists cricket_players_batting_order_check;
alter table public.cricket_players
  add constraint cricket_players_batting_order_check check (batting_order between 1 and 11);

create or replace function public.set_cricket_player_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists cricket_players_set_updated_at on public.cricket_players;
create trigger cricket_players_set_updated_at
before update on public.cricket_players
for each row execute function public.set_cricket_player_updated_at();

alter table public.cricket_players enable row level security;
drop policy if exists "public cricket players read" on public.cricket_players;
create policy "public cricket players read"
on public.cricket_players for select to anon, authenticated using (true);
grant select on public.cricket_players to anon, authenticated;

create or replace function public.save_cricket_players(p_players jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  player_id text;
  incoming_ids text[] := array[]::text[];
begin
  if jsonb_typeof(p_players) is distinct from 'array' then
    raise exception 'Cricket players must be a JSON array';
  end if;
  if jsonb_array_length(p_players) > 100 then
    raise exception 'A cricket squad supports at most 100 players';
  end if;

  for item in select value from jsonb_array_elements(p_players) loop
    player_id := btrim(item->>'id');
    if player_id is null or player_id = '' or char_length(player_id) > 80 then
      raise exception 'Every cricket player needs a valid ID';
    end if;
    if player_id = any(incoming_ids) then
      raise exception 'Cricket player IDs must be unique';
    end if;
    incoming_ids := array_append(incoming_ids, player_id);

    insert into public.cricket_players (
      client_id, name, rating, custom_overall, overall, role, batting_order, batting_hand,
      bowling_style, image_url, flag, card_style, active, batting, bowling,
      fielding, speed, power, technique, sort_order
    ) values (
      player_id,
      btrim(item->>'name'),
      coalesce((item->>'rating')::numeric, 0),
      nullif(item->>'customOverall', '')::integer,
      nullif(item->>'overall', '')::integer,
      coalesce(nullif(item->>'role', ''), 'All-rounder'),
      greatest(1, least(11, coalesce((item->>'battingOrder')::integer, 6))),
      coalesce(nullif(item->>'batting', ''), 'Right hand'),
      coalesce(nullif(item->>'bowling', ''), 'Right-arm medium'),
      nullif(item->>'image', ''),
      coalesce(nullif(item->>'flag', ''), 'PK'),
      case item->>'cardStyle'
        when 'classic' then 'classic'
        when 'royal' then 'classic'
        when 'eclipse' then 'eclipse'
        when 'prism' then 'eclipse'
        when 'crimson' then 'crimson'
        when 'inferno' then 'crimson'
        when 'electric' then 'electric'
        when 'aurora' then 'electric'
        else 'electric'
      end,
      coalesce((item->>'active')::boolean, true),
      nullif(item #>> '{stats,BAT}', '')::integer,
      nullif(item #>> '{stats,BWL}', '')::integer,
      nullif(item #>> '{stats,FLD}', '')::integer,
      nullif(item #>> '{stats,SPD}', '')::integer,
      nullif(item #>> '{stats,PWR}', '')::integer,
      nullif(item #>> '{stats,TEC}', '')::integer,
      coalesce((item->>'sortOrder')::integer, 0)
    )
    on conflict (client_id) do update set
      name = excluded.name,
      rating = excluded.rating,
      custom_overall = excluded.custom_overall,
      overall = excluded.overall,
      role = excluded.role,
      batting_order = excluded.batting_order,
      batting_hand = excluded.batting_hand,
      bowling_style = excluded.bowling_style,
      image_url = excluded.image_url,
      flag = excluded.flag,
      card_style = excluded.card_style,
      active = excluded.active,
      batting = excluded.batting,
      bowling = excluded.bowling,
      fielding = excluded.fielding,
      speed = excluded.speed,
      power = excluded.power,
      technique = excluded.technique,
      sort_order = excluded.sort_order;
  end loop;

  delete from public.cricket_players
  where not (client_id = any(incoming_ids));
end;
$$;

revoke all on function public.save_cricket_players(jsonb) from public;
grant execute on function public.save_cricket_players(jsonb) to anon, authenticated;

-- Preserve cricket players created before this dedicated table existed.
do $$
declare
  legacy_players jsonb;
begin
  select app_state #> '{cricket,players}' into legacy_players
  from public.squad_settings
  where id = 1;

  if not exists (select 1 from public.cricket_players)
    and jsonb_typeof(legacy_players) = 'array'
    and jsonb_array_length(legacy_players) > 0 then
    perform public.save_cricket_players(legacy_players);
  end if;
end $$;

-- Sport switches, teams, scores and commentary still arrive through the single
-- squad_settings row. Direct cricket-roster changes are also published.
do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'squad_settings'
  ) then
    execute 'alter publication supabase_realtime add table public.squad_settings';
  end if;
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'cricket_players'
  ) then
    execute 'alter publication supabase_realtime add table public.cricket_players';
  end if;
end $$;

commit;
