create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  rating integer not null default 75 check (rating between 50 and 99),
  available boolean not null default true,
  team integer not null default 0 check (team between 0 and 2),
  image_url text,
  sort_order integer not null default 0
);

create table if not exists public.squad_settings (
  id integer primary key,
  team_1_name text not null default 'Team 1',
  team_2_name text not null default 'Team 2'
);

insert into public.squad_settings (id, team_1_name, team_2_name)
values (1, 'Team 1', 'Team 2')
on conflict (id) do nothing;

alter table public.players enable row level security;
alter table public.squad_settings enable row level security;

drop policy if exists "public players read" on public.players;
drop policy if exists "public players write" on public.players;
drop policy if exists "public settings read" on public.squad_settings;
drop policy if exists "public settings write" on public.squad_settings;

create policy "public players read" on public.players for select to anon using (true);
create policy "public players write" on public.players for all to anon using (true) with check (true);
create policy "public settings read" on public.squad_settings for select to anon using (true);
create policy "public settings write" on public.squad_settings for all to anon using (true) with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('player-images', 'player-images', true, 5242880, array['image/jpeg','image/png','image/webp','image/gif','application/json'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public player images read" on storage.objects;
drop policy if exists "public player images upload" on storage.objects;
drop policy if exists "public player images update" on storage.objects;
drop policy if exists "public player images delete" on storage.objects;

create policy "public player images read" on storage.objects for select to anon using (bucket_id = 'player-images');
create policy "public player images upload" on storage.objects for insert to anon with check (bucket_id = 'player-images');
create policy "public player images update" on storage.objects for update to anon using (bucket_id = 'player-images') with check (bucket_id = 'player-images');
create policy "public player images delete" on storage.objects for delete to anon using (bucket_id = 'player-images');

grant select, insert, update, delete on public.players, public.squad_settings to anon;
grant usage, select on sequence public.players_id_seq to anon;

-- Save the whole shared squad in one transaction. A failed insert rolls back
-- the delete, so connection or validation errors cannot erase the old squad.
create or replace function public.save_team_maker_squad(
  p_players jsonb, p_team1_name text, p_team2_name text
) returns void language plpgsql security invoker set search_path = public as $$
declare
  item jsonb;
  position integer := 0;
begin
  if jsonb_typeof(p_players) is distinct from 'array' then
    raise exception 'Players must be an array';
  end if;
  if jsonb_array_length(p_players) > 100 then
    raise exception 'A squad supports at most 100 players';
  end if;
  if length(trim(p_team1_name)) not between 1 and 40 or
     length(trim(p_team2_name)) not between 1 and 40 then
    raise exception 'Team names must be between 1 and 40 characters';
  end if;
  -- Serialize saves to the shared squad.
  perform pg_advisory_xact_lock(7312904);
  delete from public.players;
  for item in select value from jsonb_array_elements(p_players) loop
    if length(trim(item->>'name')) not between 1 and 60 then
      raise exception 'Player names must be between 1 and 60 characters';
    end if;
    insert into public.players (name, rating, available, team, image_url, sort_order)
    values (trim(item->>'name'), (item->>'rating')::integer,
      (item->>'available')::boolean,
      case when (item->>'available')::boolean then (item->>'team')::integer else 0 end,
      nullif(item->>'imageUrl', ''), position);
    position := position + 1;
  end loop;
  insert into public.squad_settings (id, team_1_name, team_2_name)
  values (1, trim(p_team1_name), trim(p_team2_name))
  on conflict (id) do update set team_1_name = excluded.team_1_name,
    team_2_name = excluded.team_2_name;
end;
$$;
revoke execute on function public.save_team_maker_squad(jsonb, text, text) from public;
grant execute on function public.save_team_maker_squad(jsonb, text, text) to anon;
